blueprint:
  name: Always On Switch/Light - Boolean Condition
  description: Mantém os switch/lighs sempre ligados - utiliza um Boolean ou Sensor como condição
  domain: automation
  input:
    target_switch:
      name: Switches / Lights
      description: Selecione as entidades switch / light para manter sempre ligados.
      selector:
            entity:
              domain:
                - switch
                - light
              multiple: true
    boolean_condition:
      name: Boolean condition
      description: Selecione o Input Boolean para testar a condição de execução.
      selector:
            entity:
              domain:
                - sensor
                - input_boolean
              multiple: false

    update_frequency:
      name: Frequência de checagem
      description: Frequência de checagem (colocar /5 para checar de 5 em 5 minutos)
      default: "/5"
      selector:
        text:

mode: single
max_exceeded: silent

trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: !input target_switch
    to: "off"
  - platform: time_pattern
    id: temp_update
    minutes: !input update_frequency 

conditions:
  - condition: state
    entity_id: input_boolean.servidor_de_producao
    state: "on"
    
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: switch.turn_on
    entity_id: !input target_switch
