blueprint:
  name: Always On Switch/Light
  description: Mantém os switch/lighs sempre ligados
  domain: automation
  input:
    target_switch:
      name: Switches / Lights
      description: Selecione as entidades switch / light para manter sempre ligados.
      selector:
            entity:
              domain:
                - switch
                - light
              multiple: true
    update_frequency:
      name: Frequência de checagem (minutos)
      description: Frequência de checagem (minutos)
      default: "/5"
      selector:
        text:

mode: single
max_exceeded: silent

trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: !input target_switch
    to: "off"
  - platform: time_pattern
    id: temp_update
    minutes: !input update_frequency 
    
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: switch.turn_on
    entity_id: !input target_switch
