blueprint:
  name: Paralelo Virtual
  description: Liga/desliga todos os switchs/lights do grupo simultaneamente - somente se o boolean Servidor de Produção estiver ativado!
  domain: automation
  input:
    entrada_switchs:
      name: Escolha as entidades do tipo switch/light para o paralelo virtual
      selector:
            entity:
              domain:
                - switch
                - light
              multiple: true

trigger:
  platform: state
  entity_id: !input entrada_switchs

conditions:
  - condition: state
    entity_id: input_boolean.servidor_de_producao
    state: "on"

action:
  - service: >
      {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
      {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
      {% endif %}
    target:
      entity_id:
        !input entrada_switchs
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0

mode: single
